// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANQLGhAUWDqMoFFEUZNyY3GjqstmIVmjU',
    appId: '1:445095313817:web:96c2433db2669877dcd308',
    messagingSenderId: '445095313817',
    projectId: 'fyp-phase1',
    authDomain: 'fyp-phase1.firebaseapp.com',
    storageBucket: 'fyp-phase1.firebasestorage.app',
    measurementId: 'G-T5MJHK8ND7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBiKsrh4ULXVi14sEAIESeMZM0pZ42aZg',
    appId: '1:445095313817:android:0a03cae7bd51019fdcd308',
    messagingSenderId: '445095313817',
    projectId: 'fyp-phase1',
    storageBucket: 'fyp-phase1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALRhQr-C_X15GP9CNQOCtruG7KAuFgYMY',
    appId: '1:445095313817:ios:a4fd4590d9080630dcd308',
    messagingSenderId: '445095313817',
    projectId: 'fyp-phase1',
    storageBucket: 'fyp-phase1.firebasestorage.app',
    iosBundleId: 'com.example.fypPhase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALRhQr-C_X15GP9CNQOCtruG7KAuFgYMY',
    appId: '1:445095313817:ios:a4fd4590d9080630dcd308',
    messagingSenderId: '445095313817',
    projectId: 'fyp-phase1',
    storageBucket: 'fyp-phase1.firebasestorage.app',
    iosBundleId: 'com.example.fypPhase1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANQLGhAUWDqMoFFEUZNyY3GjqstmIVmjU',
    appId: '1:445095313817:web:f77cfb5eb7704bd4dcd308',
    messagingSenderId: '445095313817',
    projectId: 'fyp-phase1',
    authDomain: 'fyp-phase1.firebaseapp.com',
    storageBucket: 'fyp-phase1.firebasestorage.app',
    measurementId: 'G-5QXK1126HF',
  );
}
