// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_API_KEY_WEB'] ?? '',
        appId: '1:536136113610:web:9f8e4c73ae0ed5448373af',
        messagingSenderId: '536136113610',
        projectId: 'fyp-phase1',
        authDomain: 'fyp-phase1.firebaseapp.com',
        storageBucket: 'fyp-phase1.firebasestorage.app',
        measurementId: 'G-T5MJHK8ND7',
      );

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_API_KEY_ANDROID'] ?? '',
        appId: '1:536136113610:android:3a5fe612fd2af9fd8373af',
        messagingSenderId: '536136113610',
        projectId: 'fyp-phase1',
        storageBucket: 'fyp-phase1.firebasestorage.app',
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_API_KEY_IOS'] ?? '',
        appId: '1:536136113610:ios:db62dff7d45c5ab48373af',
        messagingSenderId: '536136113610',
        projectId: 'fyp-phase1',
        storageBucket: 'fyp-phase1.firebasestorage.app',
        iosBundleId: 'com.example.fypPhase1',
      );

  static FirebaseOptions get macos => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_API_KEY_MACOS'] ?? '',
        appId: '1:536136113610:ios:db62dff7d45c5ab48373af',
        messagingSenderId: '536136113610',
        projectId: 'fyp-phase1',
        storageBucket: 'fyp-phase1.firebasestorage.app',
        iosBundleId: 'com.example.fypPhase1',
      );

  static FirebaseOptions get windows => FirebaseOptions(
        apiKey: dotenv.env['FIREBASE_API_KEY_WINDOWS'] ?? '',
        appId: '1:536136113610:web:13010461bd2dccdc8373af',
        messagingSenderId: '536136113610',
        projectId: 'fyp-phase1',
        authDomain: 'fyp-phase1.firebaseapp.com',
        storageBucket: 'fyp-phase1.firebasestorage.app',
        measurementId: 'G-5QXK1126HF',
      );
}
